class_name AK

class EVENTS:

	const FRICTION_HAMMER_START = 2838252737 
	const FRICTION_LEVER_CREAK = 4096363487 
	const IMPACT_LIGHT_HAMMER = 160312839 
	const FRICTION_DOOR_START = 2986304931 
	const IMPACT_DOOR = 2826139286 
	const FRICTION_HAMMER_STOP = 1803454843 
	const FRICTION_DOOR_STOP = 884199073 
	const IMPACT_HEAVY_HAMMER = 1917250544 

	const _dict = { 
	 "FRICTION HAMMER START": FRICTION_HAMMER_START,
	 "FRICTION LEVER CREAK": FRICTION_LEVER_CREAK,
	 "IMPACT LIGHT HAMMER": IMPACT_LIGHT_HAMMER,
	 "FRICTION DOOR START": FRICTION_DOOR_START,
	 "IMPACT DOOR": IMPACT_DOOR,
	 "FRICTION HAMMER STOP": FRICTION_HAMMER_STOP,
	 "FRICTION DOOR STOP": FRICTION_DOOR_STOP,
	 "IMPACT HEAVY HAMMER": IMPACT_HEAVY_HAMMER
	} 

class STATES:

	const _dict = {} 

class SWITCHES:

	const _dict = {} 

class GAME_PARAMETERS:

	const SIMULATION_FA_SSGRAIN = 2428833394 
	const PHYSICS_CONTROLLER_SPEED = 420396723 
	const PHYSICS_DOOR_VELOCITY = 1455917071 
	const PHYSICS_LEVER_PULL_STRENGTH = 4280574059 
	const PROXIMITY_FA_SSGRAIN = 1791284502 
	const INSTRUMENT_FA_SSGRAIN = 2317409760 
	const RPM_FA_SSGRAIN = 1656280998 
	const IMMERSION_FA_SSGRAIN = 2481728872 
	const DENSITY_FA_SSGRAIN = 2715217995 

	const _dict = { 
	 "SIMULATION FA SSGRAIN": SIMULATION_FA_SSGRAIN,
	 "PHYSICS CONTROLLER SPEED": PHYSICS_CONTROLLER_SPEED,
	 "PHYSICS DOOR VELOCITY": PHYSICS_DOOR_VELOCITY,
	 "PHYSICS LEVER PULL STRENGTH": PHYSICS_LEVER_PULL_STRENGTH,
	 "PROXIMITY FA SSGRAIN": PROXIMITY_FA_SSGRAIN,
	 "INSTRUMENT FA SSGRAIN": INSTRUMENT_FA_SSGRAIN,
	 "RPM FA SSGRAIN": RPM_FA_SSGRAIN,
	 "IMMERSION FA SSGRAIN": IMMERSION_FA_SSGRAIN,
	 "DENSITY FA SSGRAIN": DENSITY_FA_SSGRAIN
	} 

class TRIGGERS:

	const _dict = {} 

class BANKS:

	const INIT = 1355168291 

	const _dict = { 
	 "INIT": INIT
	} 

class BUSSES:

	const MASTER_AUDIO_BUS = 3803692087 

	const _dict = { 
	 "MASTER AUDIO BUS": MASTER_AUDIO_BUS
	} 

class AUX_BUSSES:

	const _dict = {} 

class AUDIO_DEVICES:

	const SYSTEM = 3859886410 
	const NO_OUTPUT = 2317455096 

	const _dict = { 
	 "SYSTEM": SYSTEM,
	 "NO OUTPUT": NO_OUTPUT
	} 

class EXTERNAL_SOURCES:

	const _dict = {} 

